### ISSUE TITLE
BOOT switch is GPIO0, not GPIO2

### ISSUE THREAD

**Issue by bruce3322** [Zachay-NAU/ESPHome-Support-on-Seeed-Studio-XIAO-ESP32S3#1]
Hi,

For the microphone ESPHome yaml, the GPIO for the BOOT switch is GPIO0, not GPIO2 ... 
[https://files.seeedstudio.com/wiki/SeeedStudio-XIAO-ESP32S3/res/XIAO_ESP32S3_Sense_Pinout.xlsx](url)
```
...
# Configuration for the binary sensor (Boot Switch)
binary_sensor:    
  - platform: gpio
    pin: 
      number: GPIO0  #This is not GPIO2  
...
```
